server:
  port:
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: #可以设置多个路由规则
        - id:  #随便定义一个名字
          uri: http://localhost:8080#指定需要转发的地址，当符合指定的规则，就会转发到这个地址
          # 使用了nacos后，
          # uri: lb://order-service
          # lb 就是就简写的load balance


          # 断言规则
          predicates:
            - Path=/order/** #用来匹配地址的前缀,默认是将对应的/order/**放到uri之后

          filters: #为了过滤掉重新转发的地址中的不需要的内容，如之前的order
            - StripPrefix=1 # 表示去掉第一层的那个内容

      # 使用nacos后，可以使用下面的一种简便的方式
#      discovery:
#        locator:
#          enabled: true # 自动识别nacos服务
    # 虽然方便，但是上述方式并不常用
    nacos:
      discovery:
        server-addr:
        username:
        password:

