spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: 用户名
    password: 密码
    url: jdbc:mysql://localhost:3306/表名?characterEncoding=utf-8
server:
  port: 8080
  address: localhost

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:/mapperXml/*.xml
  configuration:
    map-underscore-to-camel-case: true