server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    sentinel:
      filter:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true #基于服务发现的路由规则
          lower-case-service-id: true #服务名均转化为对应的小写
      httpclient:
        connect-timeout: 10000
        response-timeout: 5s
      routes:
        - id: order-service-xx
          uri: lb://order-service
          predicates:
            - Path=/order/add/**,/order/reduct/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8889
        username: nacos
        password: nacos
        namespace: 837d0dbd-f8ca-4289-990b-4f097ea6f4ea
        group: orderGroup
#    sentinel:
#      filter:
#        enabled: false # 避免本网关功能被sentinel控制

