server:
  port: 8080

spring:
  redis:
    host: 47.99.163.246
    password: pi31415926
    port: 6389
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
    timeout: 10000
  datasource:
    username: root_wcd
    password: Pi_31415926
    url: jdbc:mysql://rm-bp13j3k8j7222149cnm.mysql.rds.aliyuncs.com:3306/tele
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:/mybatis/*.xml
logging:
  level:
    com.example.demo: debug