server:
  port: 8082

spring:
  application:
    name: stock-service #服务的名称，将被nacos用于注册
  cloud:
    nacos:
      server-addr: 
      discovery:
        username: 
        password: 
        namespace: 